#!/usr/bin/env python3

# joins two musicxml files

import sys
import xml.etree.ElementTree as ET

def combine_files(xml_file1, xml_file2, output_file):
	tree1 = ET.parse(xml_file1)
	tree2 = ET.parse(xml_file2)
	root1 = tree1.getroot()
	root2 = tree2.getroot()

	parts1 = root1.findall("./part")
	parts2 = root2.findall("./part")
	if len(parts1) != len(parts2):
		print("different number of parts")

	for i in range(len(parts2)):
		measures = parts2[i].findall("measure")
		for measure in measures:
			parts1[i].append(measure)


	tree1.write(output_file)

if len(sys.argv) != 4:
	print(f"Usage: python {sys.argv[0]} <xml_file1> <xml_file2> <output_file>")
else:
	xml_file1 = sys.argv[1]
	xml_file2 = sys.argv[2]
	output_file = sys.argv[3]
	combine_files(xml_file1, xml_file2, output_file)
